import { getUser, login, logout, handleAuthCallback, requestPasswordRecovery } from "https://esm.sh/@netlify/identity@2.0.0";

const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const money=v=>new Intl.NumberFormat("ar-MA",{style:"currency",currency:"MAD"}).format(Number(v||0));
const state={page:"overview",data:[],categories:[],editing:null,user:null};
const pages={overview:"نظرة عامة",products:"المنتجات",categories:"التصنيفات",orders:"الطلبات",customers:"الزبائن",settings:"إعدادات المتجر"};
const icons={overview:"⌂",products:"◇",categories:"▦",orders:"▤",customers:"♙",settings:"⚙"};
const nav=Object.entries(pages).map(([k,v])=>`<button class="nav-btn" data-page="${k}"><span>${icons[k]}</span>${v}</button>`).join("");
$("#nav").innerHTML=nav; $("#mobile-nav").innerHTML=nav;
const toast=m=>{const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)};
async function api(resource,opts={}){const r=await fetch(`/api/admin?resource=${resource}${opts.id?`&id=${opts.id}`:""}`,{method:opts.method||"GET",headers:opts.body?{"content-type":"application/json"}:{},body:opts.body?JSON.stringify(opts.body):undefined});const j=await r.json();if(!r.ok){if(r.status===401) showLogin();throw new Error(j.error||"تعذر إتمام العملية")}return j}
function showLogin(){ $("#login").hidden=false;$("#app").hidden=true }
function showApp(user){state.user=user;$("#login").hidden=true;$("#app").hidden=false;$("#user-email").textContent=user.email||"";$("#user-name").textContent=user.userMetadata?.full_name||"مدير المتجر";go("overview")}
async function init(){try{await handleAuthCallback();const user=await getUser();const roles=user?.appMetadata?.roles||[];user&&roles.includes("admin")?showApp(user):showLogin()}catch{showLogin()}}
$("#login-form").addEventListener("submit",async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$("#login-error").textContent="";try{const f=new FormData(e.target),u=await login(f.get("email"),f.get("password"));if(!(u.appMetadata?.roles||[]).includes("admin")){await logout();throw new Error("هذا الحساب لا يملك صلاحية المدير")};showApp(u)}catch(x){$("#login-error").textContent=x.status===401?"البريد الإلكتروني أو كلمة المرور غير صحيحة":x.message}finally{b.disabled=false}});
$("#forgot").onclick=async()=>{const email=$("#login-form").email.value;if(!email)return $("#login-error").textContent="أدخل بريدك الإلكتروني أولاً";try{await requestPasswordRecovery(email);toast("أرسلنا رابط استعادة كلمة المرور")}catch(e){$("#login-error").textContent=e.message}};
$("#logout").onclick=async()=>{await logout();showLogin()};$("#menu").onclick=()=>$("aside").classList.toggle("open");$("#close").onclick=closeDrawer;$("#overlay").addEventListener("click",e=>{if(e.target.id==="overlay")closeDrawer()});
document.addEventListener("click",e=>{const n=e.target.closest("[data-page]");if(n)go(n.dataset.page);const a=e.target.closest("[data-act]");if(a)act(a.dataset.act,Number(a.dataset.id))});
async function go(page){state.page=page;state.editing=null;$("aside").classList.remove("open");document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#title").textContent=pages[page];$("#header-action").hidden=["overview","settings"].includes(page);$("#header-action").textContent=page==="products"?"إضافة منتج":page==="orders"?"إضافة طلب":"إضافة جديد";loading();try{state.categories=await api("categories");if(page==="overview")renderOverview(await api("overview"));else if(page==="settings")renderSettings(await api("settings"));else{state.data=await api(page);renderList()}}catch(e){errorView(e.message)}}
$("#header-action").onclick=()=>openForm();function loading(){$("#content").innerHTML=`<div class="data-card">${"<div class=skeleton></div>".repeat(7)}</div>`}function errorView(m){$("#content").innerHTML=`<div class="empty"><b>تعذر تحميل البيانات</b>${esc(m)}<br><button class="primary" onclick="location.reload()">إعادة المحاولة</button></div>`}
function renderOverview(d){const s=d.stats,r=d.recent||[];$("#content").innerHTML=`<div class="welcome"><div><h2>أهلاً بك في متجرك</h2><p>هذه خلاصة أداء LMPharma الآن.</p></div><span class="date-chip">${new Intl.DateTimeFormat("ar-MA",{dateStyle:"long"}).format(new Date())}</span></div><div class="stats"><div class="stat hero-stat"><small>إجمالي المبيعات</small><strong>${money(s.sales)}</strong><span>باستثناء الطلبات الملغاة</span></div><div class="stat"><small>الطلبات</small><strong>${s.orders}</strong><span>طلب مسجل</span></div><div class="stat"><small>المنتجات</small><strong>${s.products}</strong><span>في الكتالوج</span></div><div class="stat"><small>الزبائن</small><strong>${s.customers}</strong><span>زبون</span></div></div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>نشاط المبيعات</h3><span class="badge">آخر 7 أيام</span></div><div class="bars">${[38,56,32,70,48,88,63].map((x,i)=>`<i class="bar ${i===5?"active":""}" style="height:${x}%"></i>`).join("")}</div></div><div class="panel"><div class="panel-head"><h3>أحدث الطلبات</h3></div>${r.length?r.map(o=>`<div class="status-row"><i class="dot"></i><span>${esc(o.orderNumber)}</span><b>${money(o.total)}</b></div>`).join(""):'<div class="empty">لا توجد طلبات بعد</div>'}</div></div>`}
const statuses={new:"جديد",confirmed:"مؤكد",processing:"قيد التجهيز",shipped:"تم الشحن",delivered:"تم التسليم",cancelled:"ملغي"};
function renderList(filter=""){let rows=state.data.filter(x=>JSON.stringify(x).toLowerCase().includes(filter.toLowerCase()));const cfg={products:{heads:["المنتج","التصنيف","السعر","المخزون",""],row:x=>[`<div class="product-cell">${x.images?.[0]?`<img class="thumb" src="${esc(x.images[0])}">`:'<span class="thumb">LM</span>'}<b>${esc(x.name)}</b></div>`,esc(x.categoryName||"بدون تصنيف"),money(x.price),`<span class="badge ${x.inStock?'':'danger'}">${x.inStock?'متوفر':'نفد'}</span>`,actions(x.id)]},categories:{heads:["التصنيف","الرابط","الوصف",""],row:x=>[esc(x.name),esc(x.slug),esc(x.description||"—"),actions(x.id)]},orders:{heads:["رقم الطلب","الزبون","الهاتف","الإجمالي","الحالة",""],row:x=>[esc(x.orderNumber),esc(x.customerName),esc(x.phone),money(x.total),`<span class="badge ${x.status==='cancelled'?'danger':x.status==='new'?'warn':''}">${statuses[x.status]||x.status}</span>`,actions(x.id)]},customers:{heads:["الزبون","الهاتف","العنوان","الطلبات","المشتريات",""],row:x=>[esc(x.name),esc(x.phone),esc(x.address||"—"),x.orderCount,money(x.totalSpent),actions(x.id)]}}[state.page];$("#content").innerHTML=`<div class="toolbar"><input id="search-admin" class="searchbox" placeholder="ابحث هنا..."></div><div class="data-card">${rows.length?`<table><thead><tr>${cfg.heads.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map(x=>`<tr>${cfg.row(x).map((v,i)=>`<td data-label="${cfg.heads[i]}">${v}</td>`).join("")}</tr>`).join("")}</tbody></table>`:`<div class="empty"><b>لا توجد بيانات بعد</b>استخدم زر الإضافة لبدء إدارة هذا القسم.</div>`}</div>`;$("#search-admin").oninput=e=>renderList(e.target.value)}
const actions=id=>`<div class="actions"><button data-act="edit" data-id="${id}">تعديل</button><button data-act="delete" data-id="${id}">حذف</button></div>`;
async function act(a,id){const item=state.data.find(x=>x.id===id);if(a==="edit")openForm(item);if(a==="delete"&&confirm("هل تريد حذف هذا السجل نهائياً؟")){try{await api(state.page,{method:"DELETE",id});toast("تم الحذف بنجاح");go(state.page)}catch(e){toast(e.message)}}}
const field=(label,name,type="text",value="",extra="")=>`<label class="field ${type==='textarea'?'full':''}">${label}${type==='textarea'?`<textarea name="${name}" ${extra}>${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${extra}>`}</label>`;
function openForm(item={}){state.editing=item.id||null;$("#drawer-title").textContent=item.id?"تعديل السجل":"إضافة جديد";let h="";if(state.page==="products")h=field("اسم المنتج","name","text",item.name,"required")+field("السعر (MAD)","price","number",item.price,"required min=0 step=.01")+field("السعر القديم","oldPrice","number",item.oldPrice,"min=0 step=.01")+field("التخفيض %","discount","number",item.discount||0,"min=0 max=100")+`<label class="field">التصنيف<select name="categoryId"><option value="">بدون تصنيف</option>${state.categories.map(c=>`<option value="${c.id}" ${c.id===item.categoryId?'selected':''}>${esc(c.name)}</option>`).join("")}</select></label>`+field("الوصف","description","textarea",item.description)+`<label class="field image-field">صور المنتج<input id="images" type="file" accept="image/*" multiple><div class="image-preview">${(item.images||[]).map(x=>`<img src="${esc(x)}">`).join("")}</div></label><label class="switch-field"><input name="inStock" type="checkbox" ${item.inStock!==false?'checked':''}> متوفر في المخزون</label><label class="switch-field"><input name="featured" type="checkbox" ${item.featured?'checked':''}> منتج مميز</label><input name="existingImages" type="hidden" value='${esc(JSON.stringify(item.images||[]))}'>`;else if(state.page==="categories")h=field("اسم التصنيف","name","text",item.name,"required")+field("الوصف","description","textarea",item.description);else if(state.page==="customers")h=field("اسم الزبون","name","text",item.name,"required")+field("رقم الهاتف","phone","tel",item.phone,"required")+field("العنوان","address","textarea",item.address);else if(state.page==="orders")h=field("رقم الطلب","orderNumber","text",item.orderNumber)+field("اسم الزبون","customerName","text",item.customerName,"required")+field("الهاتف","phone","tel",item.phone,"required")+field("العنوان","address","textarea",item.address)+field("الإجمالي (MAD)","total","number",item.total,"required min=0 step=.01")+`<label class="field">الحالة<select name="status">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${k===item.status?'selected':''}>${v}</option>`).join("")}</select></label>`+field("المنتجات (كل منتج في سطر)","productLines","textarea",(item.products||[]).map(x=>`${x.name}|${x.quantity}|${x.price}`).join("\n"),"placeholder='المنتج|الكمية|السعر'")+field("ملاحظات","notes","textarea",item.notes);$("#entity-form").innerHTML=h+`<div class="form-actions"><button class="primary" type="submit">حفظ البيانات</button><button class="secondary" type="button" id="cancel">إلغاء</button></div>`;$("#overlay").hidden=false;$("#cancel").onclick=closeDrawer;$("#entity-form").onsubmit=saveForm}
function closeDrawer(){$("#overlay").hidden=true}
async function saveForm(e){e.preventDefault();const b=e.submitter;b.disabled=true;const f=new FormData(e.target),body=Object.fromEntries(f);if(state.page==="products"){body.inStock=f.has("inStock");body.featured=f.has("featured");body.images=JSON.parse(body.existingImages||"[]");delete body.existingImages;const files=[...$("#images").files];for(const file of files){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/admin-media",{method:"POST",body:fd}),j=await r.json();if(!r.ok){toast(j.error);b.disabled=false;return}body.images.push(j.url)}}if(state.page==="orders")body.products=String(body.productLines||"").split("\n").filter(Boolean).map(x=>{const [name,quantity,price]=x.split("|");return{name,quantity:Number(quantity||1),price:Number(price||0)}});try{await api(state.page,{method:state.editing?"PUT":"POST",id:state.editing,body});closeDrawer();toast("تم حفظ البيانات");go(state.page)}catch(x){toast(x.message);b.disabled=false}}
function renderSettings(x){$("#content").innerHTML=`<div class="panel"><form id="settings-form" style="display:grid;grid-template-columns:1fr 1fr;gap:16px">${field("اسم المتجر","storeName","text",x.storeName||"LMPharma","required")}${field("الهاتف","phone","tel",x.phone)}${field("واتساب","whatsapp","tel",x.whatsapp)}${field("العنوان","address","textarea",x.address)}${field("رسوم التوصيل (MAD)","deliveryFee","number",x.deliveryFee,"min=0 step=.01")}${field("حد التوصيل المجاني","freeDeliveryThreshold","number",x.freeDeliveryThreshold,"min=0 step=.01")}<button class="primary" type="submit">حفظ الإعدادات</button></form></div>`;$("#settings-form").onsubmit=async e=>{e.preventDefault();try{await api("settings",{method:"PUT",body:Object.fromEntries(new FormData(e.target))});toast("تم حفظ الإعدادات")}catch(x){toast(x.message)}}}
init();
